interface Food {
  id: number;
  name: string;
  water: number;
  energy: number;
  carbohydrate: number;
  protein: number;
  fat: number;
  fibre: number;
  foodTypeId: number;
}

export const foodData: Food[] = [
  {
    id: 1,
    name: "Alpukat, segar",
    water: 84.3,
    energy: 85,
    protein: 0.9,
    fat: 6.5,
    carbohydrate: 7.7,
    fibre: 0, // Set undefined to 0
    foodTypeId: 1,
  },
  {
    id: 2,
    name: "Anggur hutan, segar",
    water: 92.3,
    energy: 30,
    protein: 0.5,
    fat: 0.2,
    carbohydrate: 6.8,
    fibre: 1.2,
    foodTypeId: 1,
  },
  {
    id: 3,
    name: "Apel malang, segar",
    water: 85.9,
    energy: 57,
    protein: 0.5,
    fat: 0.4,
    carbohydrate: 12.8,
    fibre: 0.8,
    foodTypeId: 1,
  },
  {
    id: 4,
    name: "Apel, segar",
    water: 84.1,
    energy: 58,
    protein: 0.3,
    fat: 0.4,
    carbohydrate: 14.9,
    fibre: 2.6,
    foodTypeId: 1,
  },
  {
    id: 5,
    name: "Arbai, segar",
    water: 89.9,
    energy: 37,
    protein: 0.8,
    fat: 0.5,
    carbohydrate: 8.3,
    fibre: 0, // Set undefined to 0
    foodTypeId: 1,
  },
  {
    id: 6,
    name: "Barongko",
    water: 66.7,
    energy: 159,
    protein: 3.1,
    fat: 5.8,
    carbohydrate: 23.5,
    fibre: 0, // Set undefined to 0
    foodTypeId: 1,
  },
  {
    id: 7,
    name: "Belimbing, segar",
    water: 90.0,
    energy: 36,
    protein: 0.4,
    fat: 0.4,
    carbohydrate: 8.8,
    fibre: 3.3,
    foodTypeId: 1,
  },
  {
    id: 8,
    name: "Biwah, segar",
    water: 87.1,
    energy: 51,
    protein: 0.3,
    fat: 0.1,
    carbohydrate: 12.1,
    fibre: 0.7,
    foodTypeId: 1,
  },
  {
    id: 9,
    name: "Blewah, segar",
    water: 90.2,
    energy: 34,
    protein: 0.8,
    fat: 0.2,
    carbohydrate: 8.2,
    fibre: 0.9,
    foodTypeId: 1,
  },
  {
    id: 10,
    name: "Buah atung, segar",
    water: 92.0,
    energy: 23,
    protein: 0.8,
    fat: 0.2,
    carbohydrate: 5.2,
    fibre: 0, // Set undefined to 0
    foodTypeId: 1,
  },
  {
    id: 11,
    name: "Asam arang coklat, segar",
    water: 66.1,
    energy: 130,
    protein: 0.5,
    fat: 1.1,
    carbohydrate: 30.9,
    fibre: 1.5,
    foodTypeId: 2,
  },
  {
    id: 12,
    name: "Asam arang merah, segar",
    water: 75.9,
    energy: 99,
    protein: 0.8,
    fat: 1.6,
    carbohydrate: 20.3,
    fibre: 2.8,
    foodTypeId: 2,
  },
  {
    id: 13,
    name: "Asam kandis, kering",
    water: 32.2,
    energy: 261,
    protein: 0.9,
    fat: 1.6,
    carbohydrate: 63.3,
    fibre: 5.0,
    foodTypeId: 2,
  },
  {
    id: 14,
    name: "Asam kandis, segar",
    water: 81.5,
    energy: 75,
    protein: 0.2,
    fat: 1.1,
    carbohydrate: 16.1,
    fibre: 3.4,
    foodTypeId: 2,
  },
  {
    id: 15,
    name: "Asam masak pohon, segar",
    water: 31.4,
    energy: 267,
    protein: 2.8,
    fat: 0.6,
    carbohydrate: 62.5,
    fibre: 1.2,
    foodTypeId: 2,
  },
  {
    id: 16,
    name: "Asam payak, segar",
    water: 65.1,
    energy: 135,
    protein: 0.8,
    fat: 0.4,
    carbohydrate: 32.1,
    fibre: 10.0,
    foodTypeId: 2,
  },
  {
    id: 17,
    name: "Balichong",
    water: 59.9,
    energy: 152,
    protein: 13.2,
    fat: 0.8,
    carbohydrate: 22.9,
    fibre: 1.5,
    foodTypeId: 2,
  },
  {
    id: 18,
    name: "Bawang merah, segar",
    water: 88.0,
    energy: 46,
    protein: 1.5,
    fat: 0.3,
    carbohydrate: 9.2,
    fibre: 1.7,
    foodTypeId: 2,
  },
  {
    id: 19,
    name: "Bawang putih, segar",
    water: 71.0,
    energy: 112,
    protein: 4.5,
    fat: 0.2,
    carbohydrate: 23.1,
    fibre: 0.6,
    foodTypeId: 2,
  },
  {
    id: 20,
    name: "Bekasam",
    water: 65.5,
    energy: 116,
    protein: 11.9,
    fat: 4.9,
    carbohydrate: 6.1,
    fibre: 3.5,
    foodTypeId: 2,
  },
  {
    id: 21,
    name: "Anak sapi, daging, gemuk, segar",
    water: 62.0,
    energy: 184,
    protein: 18.8,
    fat: 14.0,
    carbohydrate: 0.0,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 22,
    name: "Anak sapi, daging, kurus, segar",
    water: 69.0,
    energy: 184,
    protein: 18.8,
    fat: 19.6,
    carbohydrate: 0.0,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 23,
    name: "Anak sapi, daging, sedang, segar",
    water: 68.0,
    energy: 190,
    protein: 19.1,
    fat: 12.0,
    carbohydrate: 0.0,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 24,
    name: "Angsa, daging, segar",
    water: 51.1,
    energy: 349,
    protein: 16.4,
    fat: 31.5,
    carbohydrate: 0.0,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 25,
    name: "Ayam goreng church texas, dada",
    water: 42.2,
    energy: 338,
    protein: 35.2,
    fat: 20.6,
    carbohydrate: 0.4,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 26,
    name: "Ayam goreng church texas, sayap",
    water: 47.2,
    energy: 295,
    protein: 34.0,
    fat: 16.0,
    carbohydrate: 1.5,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 27,
    name: "Ayam goreng church,texas paha",
    water: 50.3,
    energy: 287,
    protein: 31.0,
    fat: 15.7,
    carbohydrate: 1.7,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 28,
    name: "Ayam goreng kalasan, paha",
    water: 46.2,
    energy: 275,
    protein: 37.4,
    fat: 12.2,
    carbohydrate: 1.3,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 29,
    name: "Ayam goreng kentucky, dada",
    water: 46.5,
    energy: 298,
    protein: 34.2,
    fat: 16.8,
    carbohydrate: 0.1,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 30,
    name: "Ayam goreng Kentucky, paha",
    water: 48.7,
    energy: 286,
    protein: 32.1,
    fat: 16.1,
    carbohydrate: 1.1,
    fibre: 0,
    foodTypeId: 3,
  },
  {
    id: 31,
    name: "Abon haruwan",
    water: 11.6,
    energy: 513,
    protein: 23.7,
    fat: 37.0,
    carbohydrate: 21.3,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 32,
    name: "Abon ikan",
    water: 6.4,
    energy: 435,
    protein: 27.2,
    fat: 20.2,
    carbohydrate: 36.1,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 33,
    name: "Bekicot, dendeng, mentah",
    water: 6.7,
    energy: 441,
    protein: 48.7,
    fat: 20.3,
    carbohydrate: 15.8,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 34,
    name: "Belut, goreng",
    water: 11.2,
    energy: 417,
    protein: 25.9,
    fat: 19.4,
    carbohydrate: 32.0,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 35,
    name: "Belut, segar",
    water: 81.5,
    energy: 70,
    protein: 14.6,
    fat: 0.8,
    carbohydrate: 1.0,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 36,
    name: "Belut laut, segar",
    water: 79.5,
    energy: 93,
    protein: 12.8,
    fat: 1.5,
    carbohydrate: 6.1,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 37,
    name: "Betok wadi, masakan",
    water: 69.2,
    energy: 145,
    protein: 16.3,
    fat: 7.0,
    carbohydrate: 4.1,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 38,
    name: "Bou ninahu ndamate, masakan",
    water: 79.1,
    energy: 79,
    protein: 6.3,
    fat: 1.0,
    carbohydrate: 1.1,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 39,
    name: "Bouiki ninahu nggaluku, masakan",
    water: 73.9,
    energy: 94,
    protein: 7.8,
    fat: 2.2,
    carbohydrate: 10.8,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 40,
    name: "Cakalang asar (asap papua)",
    water: 64.3,
    energy: 155,
    protein: 20.1,
    fat: 3.8,
    carbohydrate: 10.2,
    fibre: 0,
    foodTypeId: 4,
  },
  {
    id: 41,
    name: "Ampas kacang hijau",
    water: 70.6,
    energy: 96,
    protein: 3.7,
    fat: 0.6,
    carbohydrate: 19.1,
    fibre: 2.7,
    foodTypeId: 5,
  },
  {
    id: 42,
    name: "Ampas tahu kukus",
    water: 82.5,
    energy: 75,
    protein: 4.1,
    fat: 2.1,
    carbohydrate: 10.7,
    fibre: 5.1,
    foodTypeId: 5,
  },
  {
    id: 43,
    name: "Ampas tahu, kering",
    water: 9.0,
    energy: 414,
    protein: 26.6,
    fat: 18.3,
    carbohydrate: 41.3,
    fibre: 0,
    foodTypeId: 5,
  },
  {
    id: 44,
    name: "Ampas tahu, mentah",
    water: 84.1,
    energy: 67,
    protein: 5.0,
    fat: 2.1,
    carbohydrate: 8.1,
    fibre: 4.1,
    foodTypeId: 5,
  },
  {
    id: 45,
    name: "Bungkil biji karet",
    water: 12.0,
    energy: 333,
    protein: 29.3,
    fat: 3.3,
    carbohydrate: 50.0,
    fibre: 0,
    foodTypeId: 5,
  },
  {
    id: 46,
    name: "Bungkil kacang tanah",
    water: 14.0,
    energy: 336,
    protein: 37.4,
    fat: 13.0,
    carbohydrate: 30.5,
    fibre: 0,
    foodTypeId: 5,
  },
  {
    id: 47,
    name: "Bungkil kelapa",
    water: 16.0,
    energy: 368,
    protein: 23.0,
    fat: 15.0,
    carbohydrate: 40.0,
    fibre: 0,
    foodTypeId: 5,
  },
  {
    id: 48,
    name: "Dodol banjarmasin",
    water: 17.3,
    energy: 368,
    protein: 2.6,
    fat: 8.6,
    carbohydrate: 70.0,
    fibre: 0.5,
    foodTypeId: 5,
  },
  {
    id: 49,
    name: "Emping (kerupuk melinjo)",
    water: 13.0,
    energy: 345,
    protein: 12.0,
    fat: 1.5,
    carbohydrate: 71.5,
    fibre: 0,
    foodTypeId: 5,
  },
  {
    id: 50,
    name: "Emping komak",
    water: 14.2,
    energy: 355,
    protein: 17.8,
    fat: 4.6,
    carbohydrate: 60.7,
    fibre: 0,
    foodTypeId: 5,
  },
  {
    id: 51,
    name: "Coklat bubuk",
    water: 3.9,
    energy: 311,
    protein: 8.0,
    fat: 4.0,
    carbohydrate: 48.9,
    fibre: 32.6,
    foodTypeId: 6,
  },
  {
    id: 52,
    name: "Coklat manis, batang",
    water: 1.4,
    energy: 527,
    protein: 2.0,
    fat: 29.8,
    carbohydrate: 62.7,
    fibre: 6.5,
    foodTypeId: 6,
  },
  {
    id: 53,
    name: "Coklat pahit, batang",
    water: 2.3,
    energy: 615,
    protein: 5.5,
    fat: 42.6,
    carbohydrate: 29.2,
    fibre: 10.8,
    foodTypeId: 6,
  },
  {
    id: 54,
    name: "Coklat susu, batang",
    water: 1.0,
    energy: 565,
    protein: 9.0,
    fat: 35.0,
    carbohydrate: 53.6,
    fibre: 3.4,
    foodTypeId: 6,
  },
  {
    id: 55,
    name: "Gula aren",
    water: 7.0,
    energy: 368,
    protein: 0,
    fat: 0,
    carbohydrate: 92.0,
    fibre: 0,
    foodTypeId: 6,
  },
  {
    id: 56,
    name: "Gula kelapa",
    water: 10.0,
    energy: 386,
    protein: 3.0,
    fat: 10.0,
    carbohydrate: 76.0,
    fibre: 0,
    foodTypeId: 6,
  },
  {
    id: 57,
    name: "Gula putih",
    water: 5.4,
    energy: 394,
    protein: 0,
    fat: 0,
    carbohydrate: 94.0,
    fibre: 0,
    foodTypeId: 6,
  },
  {
    id: 58,
    name: "Jam, selai",
    water: 34.0,
    energy: 239,
    protein: 0.5,
    fat: 0.6,
    carbohydrate: 64.5,
    fibre: 1.0,
    foodTypeId: 6,
  },
  {
    id: 59,
    name: "Kopi bubuk instant",
    water: 2.6,
    energy: 129,
    protein: 12.3,
    fat: 0.5,
    carbohydrate: 35.0,
    fibre: 0,
    foodTypeId: 6,
  },
  {
    id: 60,
    name: "Madu",
    water: 20.0,
    energy: 294,
    protein: 0.3,
    fat: 0,
    carbohydrate: 79.5,
    fibre: 0.2,
    foodTypeId: 6,
  },
  {
    id: 61,
    name: "Kelapa muda, air, segar",
    water: 95.5,
    energy: 17,
    protein: 0.2,
    fat: 0.1,
    carbohydrate: 3.8,
    fibre: 0,
    foodTypeId: 7,
  },
  {
    id: 62,
    name: "Kelapa setengah tua, daging, segar",
    water: 70.0,
    energy: 180,
    protein: 4.0,
    fat: 15.0,
    carbohydrate: 10.0,
    fibre: 2.4,
    foodTypeId: 8,
  },
  {
    id: 63,
    name: "Kelapa tua, daging, segar",
    water: 46.9,
    energy: 359,
    protein: 3.4,
    fat: 34.7,
    carbohydrate: 14.0,
    fibre: 4.7,
    foodTypeId: 8,
  },
  {
    id: 64,
    name: "Lemak babi (bacon)",
    water: 20.0,
    energy: 626,
    protein: 9.1,
    fat: 65.0,
    carbohydrate: 1.1,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 65,
    name: "Lemak babi (lard)",
    water: 0,
    energy: 902,
    protein: 0,
    fat: 100.0,
    carbohydrate: 0,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 66,
    name: "Lemak ikan",
    water: 43.3,
    energy: 372,
    protein: 12.0,
    fat: 29.4,
    carbohydrate: 14.4,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 67,
    name: "Lemak kerbau (lemak sapi)",
    water: 5.0,
    energy: 818,
    protein: 1.5,
    fat: 90.0,
    carbohydrate: 0,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 68,
    name: "Margarin",
    water: 15.5,
    energy: 720,
    protein: 0.6,
    fat: 81.0,
    carbohydrate: 0.4,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 69,
    name: "Mentega",
    water: 16.0,
    energy: 742,
    protein: 0.5,
    fat: 81.6,
    carbohydrate: 1.4,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 70,
    name: "Minyak hiu, hati",
    water: 0,
    energy: 902,
    protein: 0,
    fat: 100.0,
    carbohydrate: 0,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 71,
    name: "Minyak ikan",
    water: 0,
    energy: 902,
    protein: 0,
    fat: 100.0,
    carbohydrate: 0,
    fibre: 0,
    foodTypeId: 8,
  },
  {
    id: 72,
    name: "Akar tonjong, segar",
    water: 86.7,
    energy: 45,
    protein: 1.1,
    fat: 0.4,
    carbohydrate: 10.8,
    fibre: 1.2,
    foodTypeId: 9,
  },
  {
    id: 73,
    name: "ale, toge, segar",
    water: 90.6,
    energy: 37,
    protein: 4.4,
    fat: 0.5,
    carbohydrate: 3.8,
    fibre: 1.7,
    foodTypeId: 9,
  },
  {
    id: 74,
    name: "Andaliman, segar",
    water: 74.2,
    energy: 99,
    protein: 4.6,
    fat: 1.0,
    carbohydrate: 18.0,
    fibre: 8.5,
    foodTypeId: 9,
  },
  {
    id: 75,
    name: "Andewi, segar",
    water: 91.8,
    energy: 226,
    protein: 1.6,
    fat: 0.2,
    carbohydrate: 5.3,
    fibre: 4.1,
    foodTypeId: 9,
  },
  {
    id: 76,
    name: "Anyang, sayut",
    water: 76.9,
    energy: 126,
    protein: 3.4,
    fat: 7.9,
    carbohydrate: 10.3,
    fibre: 5.4,
    foodTypeId: 9,
  },
  {
    id: 77,
    name: "Ares, sayur",
    water: 77.7,
    energy: 113,
    protein: 0.9,
    fat: 7.2,
    carbohydrate: 11.2,
    fibre: 4.7,
    foodTypeId: 9,
  },
  {
    id: 78,
    name: "Arwan sirsir",
    water: 59.0,
    energy: 227,
    protein: 2.4,
    fat: 25.0,
    carbohydrate: 10.7,
    fibre: 4.6,
    foodTypeId: 9,
  },
  {
    id: 79,
    name: "Asinan Bogor, sayuran",
    water: 78.0,
    energy: 98,
    protein: 3.9,
    fat: 2.6,
    carbohydrate: 14.8,
    fibre: 0.5,
    foodTypeId: 9,
  },
  {
    id: 80,
    name: "Bakung, segar",
    water: 92.5,
    energy: 27,
    protein: 2.0,
    fat: 0.2,
    carbohydrate: 4.2,
    fibre: 3.8,
    foodTypeId: 9,
  },
  {
    id: 81,
    name: "Baligo, segar",
    water: 96.1,
    energy: 15.0,
    protein: 0.4,
    fat: 0.2,
    carbohydrate: 3.0,
    fibre: 0.4,
    foodTypeId: 9,
  },
  {
    id: 82,
    name: "Amparan tatak",
    water: 58.4,
    energy: 191,
    protein: 1.3,
    fat: 5.5,
    carbohydrate: 34.0,
    fibre: 0,
    foodTypeId: 10,
  },
  {
    id: 83,
    name: "Apang kukus, kue",
    water: 49.5,
    energy: 202,
    protein: 3.0,
    fat: 0.3,
    carbohydrate: 46.7,
    fibre: 0,
    foodTypeId: 10,
  },
  {
    id: 84,
    name: "Apem, kue",
    water: 63.1,
    energy: 148,
    protein: 2.0,
    fat: 0.5,
    carbohydrate: 33.9,
    fibre: 0,
    foodTypeId: 10,
  },
  {
    id: 85,
    name: "Bakpia, kue",
    water: 63.1,
    energy: 148,
    protein: 8.7,
    fat: 6.7,
    carbohydrate: 44.1,
    fibre: 0.9,
    foodTypeId: 10,
  },
  {
    id: 86,
    name: "Bakwan",
    water: 40.5,
    energy: 280,
    protein: 8.2,
    fat: 10.2,
    carbohydrate: 39.0,
    fibre: 3.4,
    foodTypeId: 10,
  },
  {
    id: 87,
    name: "Bantal",
    water: 52.3,
    energy: 190,
    protein: 3.3,
    fat: 0.3,
    carbohydrate: 79.3,
    fibre: 0,
    foodTypeId: 10,
  },
  {
    id: 88,
    name: "Baruasa",
    water: 5.3,
    energy: 417,
    protein: 6.5,
    fat: 8.2,
    carbohydrate: 79.3,
    fibre: 0,
    foodTypeId: 10,
  },
  {
    id: 89,
    name: "Batar daan",
    water: 75.3,
    energy: 107,
    protein: 2.2,
    fat: 2.2,
    carbohydrate: 19.6,
    fibre: 0,
    foodTypeId: 10,
  },
  {
    id: 90,
    name: "Beras giling var pelita, mentah",
    water: 11.4,
    energy: 369,
    protein: 9.5,
    fat: 1.4,
    carbohydrate: 77.1,
    fibre: 0.4,
    foodTypeId: 10,
  },
  {
    id: 91,
    name: "Beras giling var rojolele, mentah",
    water: 12.0,
    energy: 357,
    protein: 8.4,
    fat: 1.7,
    carbohydrate: 77.1,
    fibre: 0.2,
    foodTypeId: 10,
  },
  {
    id: 92,
    name: "Es krim",
    water: 62.1,
    energy: 210,
    protein: 4.0,
    fat: 12.5,
    carbohydrate: 20.6,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 93,
    name: "Hangop",
    water: 84.0,
    energy: 65,
    protein: 10.0,
    fat: 1.0,
    carbohydrate: 3.5,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 94,
    name: "Keju",
    water: 38.5,
    energy: 326,
    protein: 22.8,
    fat: 20.3,
    carbohydrate: 13.1,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 95,
    name: "Kepala susu-krim, segar",
    water: 72.5,
    energy: 204,
    protein: 2.6,
    fat: 20.0,
    carbohydrate: 4.0,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 96,
    name: "Kwark (Quark)",
    water: 59.0,
    energy: 242,
    protein: 19.0,
    fat: 17.0,
    carbohydrate: 3.0,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 97,
    name: "Susu asam untuk bayi, bubuk",
    water: 2.5,
    energy: 418,
    protein: 19.0,
    fat: 9.0,
    carbohydrate: 65.5,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 98,
    name: "Susu bubuk",
    water: 3.5,
    energy: 513,
    protein: 24.6,
    fat: 30.0,
    carbohydrate: 36.2,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 99,
    name: "Susu ibu - ASI",
    water: 88.1,
    energy: 62,
    protein: 1.5,
    fat: 3.2,
    carbohydrate: 7.0,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 100,
    name: "Susu kambing, segar",
    water: 85.9,
    energy: 64,
    protein: 4.3,
    fat: 2.3,
    carbohydrate: 6.6,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 101,
    name: "Susu kental manis",
    water: 25.0,
    energy: 343,
    protein: 8.2,
    fat: 10.0,
    carbohydrate: 55.0,
    fibre: 0,
    foodTypeId: 11,
  },
  {
    id: 102,
    name: "Bayau mi balu, masakan",
    water: 36.1,
    energy: 313,
    protein: 6.0,
    fat: 12.2,
    carbohydrate: 44.8,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 103,
    name: "Cucuru bayau, masakan",
    water: 35.0,
    energy: 349,
    protein: 6.8,
    fat: 18.7,
    carbohydrate: 38.3,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 104,
    name: "Ikan, telut, asin, mentah",
    water: 37.8,
    energy: 358,
    protein: 20.7,
    fat: 26.4,
    carbohydrate: 9.4,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 105,
    name: "Kalio telur, masakan",
    water: 79.0,
    energy: 193,
    protein: 10.6,
    fat: 12.4,
    carbohydrate: 9.7,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 106,
    name: "Telur ayam kampung, segar",
    water: 73.1,
    energy: 174,
    protein: 10.8,
    fat: 14.0,
    carbohydrate: 1.2,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 107,
    name: "Telur ayam ras, bagian kuning, segar",
    water: 49.4,
    energy: 355,
    protein: 16.3,
    fat: 31.9,
    carbohydrate: 0.7,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 108,
    name: "Telur ayam ras, bagian putih, segar",
    water: 87.8,
    energy: 50,
    protein: 10.8,
    fat: 0,
    carbohydrate: 0.8,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 109,
    name: "Telur ayam ras, segar",
    water: 74.3,
    energy: 154,
    protein: 12.4,
    fat: 10.8,
    carbohydrate: 0.7,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 110,
    name: "Telur ayam, dadar, masakan",
    water: 61.9,
    energy: 251,
    protein: 16.3,
    fat: 19.4,
    carbohydrate: 1.4,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 111,
    name: "Telur bebek alabio, segar",
    water: 70.0,
    energy: 187,
    protein: 11.8,
    fat: 14.2,
    carbohydrate: 3.0,
    fibre: 0,
    foodTypeId: 12,
  },
  {
    id: 112,
    name: "Arrowroot, segar",
    water: 73.5,
    energy: 102,
    protein: 1.0,
    fat: 0.2,
    carbohydrate: 24.1,
    fibre: 1.7,
    foodTypeId: 13,
  },
  {
    id: 113,
    name: "Bagea kelapa asin",
    water: 3.5,
    energy: 450,
    protein: 3.2,
    fat: 13.9,
    carbohydrate: 78.1,
    fibre: 0,
    foodTypeId: 13,
  },
  {
    id: 114,
    name: "Bagea kelapa manis",
    water: 3.0,
    energy: 452,
    protein: 1.3,
    fat: 13.8,
    carbohydrate: 80.6,
    fibre: 0,
    foodTypeId: 13,
  },
  {
    id: 115,
    name: "Bagea kenari asin",
    water: 2.8,
    energy: 529,
    protein: 3.2,
    fat: 29.1,
    carbohydrate: 63.6,
    fibre: 0,
    foodTypeId: 13,
  },
  {
    id: 116,
    name: "Bagea kenari manis",
    water: 3.1,
    energy: 523,
    protein: 3.2,
    fat: 28.2,
    carbohydrate: 64.2,
    fibre: 0,
    foodTypeId: 13,
  },
  {
    id: 117,
    name: "Bagea kw 1",
    water: 7.2,
    energy: 416,
    protein: 6.5,
    fat: 9.4,
    carbohydrate: 76.3,
    fibre: 0.4,
    foodTypeId: 13,
  },
  {
    id: 118,
    name: "Bagea kw 2",
    water: 7.9,
    energy: 382,
    protein: 0.3,
    fat: 3.5,
    carbohydrate: 87.2,
    fibre: 0.9,
    foodTypeId: 13,
  },
  {
    id: 119,
    name: "Batatas gembili, segar",
    water: 76.7,
    energy: 76,
    protein: 1.1,
    fat: 0.9,
    carbohydrate: 16.0,
    fibre: 4.2,
    foodTypeId: 13,
  },
  {
    id: 120,
    name: "Batatas kelapa, ubi, bakar",
    water: 73.2,
    energy: 110,
    protein: 1.4,
    fat: 1.1,
    carbohydrate: 23.4,
    fibre: 4.5,
    foodTypeId: 13,
  },
  {
    id: 121,
    name: "Batatas kelapa, ubi, kukus",
    water: 75.7,
    energy: 92,
    protein: 1.2,
    fat: 0.3,
    carbohydrate: 21.0,
    fibre: 4.0,
    foodTypeId: 13,
  },
];
